// USER Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

// GROCERIES
export const GROCERIES_LOADING = 'GROCERIES_LOADING';
export const GROCERIES_LOADED = 'GROCERIES_LOADED';
export const ADD_GROCERY = 'ADD_GROCERY';
export const GROCERY_DELETED = 'GROCERY_DELETED';

// SCHEDULES
export const SCHEDULES_LOADING = 'SCHEDULES_LOADING';
export const SCHEDULES_LOADED = 'SCHEDULES_LOADED';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const SCHEDULE_DELETED = 'SCHEDULE_DELETED';

// UI Reducer Types
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
